import {Hermesaki} from '../client.js';
const $=s=>document.querySelector(s);
let owner, mailbox, settings, inbox, token, offset=0, tokenOffset=0, busy=false, generation=0;
function show(id){for(const x of ['login','create','connect'])$('#'+x).hidden=x!==id;}
function notice(text,error=false){$('#status').textContent=text;$('#status').className=error?'error':'';}
const errors={invalid_token:'This token has expired or was revoked. Connect again or issue a new token.',scope_denied:'This token does not have the required permission.',mailbox_denied:'This token belongs to another inbox.',connection_failed:'Could not reach the server. Check your connection and retry.',service_unavailable:'The mail service is unavailable. Your inbox address is preserved; retry when it is back.',invalid_address:'Use a valid address on this server’s domain.',access_required:'Sign in through Cloudflare Access, then retry.'};
async function run(label,fn){if(busy)return;busy=true;notice(label);$('#status').className='busy';$('.wizard').setAttribute('aria-busy','true');document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();if($('#status').className==='busy')notice('');}catch(e){notice(errors[e.code]||'Could not complete that action. Check the details and retry.',true);}finally{busy=false;$('.wizard').setAttribute('aria-busy','false');document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function client(raw){return new Hermesaki({baseUrl:location.origin,token:raw});}
$('#token-file').onchange=async()=>{const f=$('#token-file').files[0];if(f&&f.size<16384)$('#owner-token').value=(await f.text()).trim();};
$('#login-form').onsubmit=e=>{e.preventDefault();run('Checking owner access…',async()=>{const candidate=client($('#owner-token').value.trim());settings=await candidate.settings();owner=candidate;$('#owner-token').value='';$('#token-file').value='';$('#environment').textContent=settings.mode==='development'?'Local mail. External recipients are captured.':'Live mail server.';$('#domain').textContent='@'+settings.domain;$('#logout').hidden=false;await list();show('create');});};
function row(text,label,action){const div=document.createElement('div');div.className='row';const span=document.createElement('span');span.textContent=text;const b=document.createElement('button');b.className='back';b.textContent=label;b.onclick=action;div.append(span,b);return div;}
async function list(more=false){if(!more){offset=0;$('#inboxes').replaceChildren();}const p=await owner.listInboxes(offset);for(const i of p.items.filter(i=>i.active))$('#inboxes').append(row(i.email,'Manage',()=>run('Opening inbox…',()=>open(i))));if(!$('#inboxes').children.length)$('#inboxes').textContent='No inboxes yet. Create your first one above.';offset+=50;$('#more').hidden=!p.has_more;}
async function open(i){generation++;testKey=undefined;inbox=i;token=null;mailbox=null;$('#mail-token').value='';$('#snippet').textContent='';$('#issued').hidden=true;$('#checked').hidden=true;$('#messages').replaceChildren();$('#message-body').hidden=true;$('#delete-email').value='';$('#inbox-email').textContent=i.email;show('connect');await tokens();}
$('#create-form').onsubmit=e=>{e.preventDefault();run('Creating the mailbox…',async()=>{const i=await owner.createInbox($('#local-name').value+'@'+settings.domain);$('#new-scope').value=$('#scope').value;await open(i);await issue();});};
async function issue(){token=await owner.createToken(inbox.id,$('#new-scope').value==='read'?['mail.read']:['mail.read','mail.write']);mailbox=client(token.token);$('#mail-token').value=token.token;$('#issued').hidden=false;$('#checked').hidden=true;snippet();await tokens();}
$('#issue').onclick=()=>run('Issuing mailbox token…',issue);
function snippet(){const url=settings.public_url;const id=inbox.id;const examples={MCP:JSON.stringify({url:url+'/mcp',headers:{Authorization:'Bearer YOUR_MAILBOX_TOKEN'}},null,2),TypeScript:`import { Hermesaki } from '@hermesaki/client';\nconst mail = new Hermesaki({\n  baseUrl: '${url}',\n  token: process.env.HERMESAKI_TOKEN\n});\nawait mail.listMessages('${id}');`,CLI:`export HERMESAKI_URL='${url}'\nexport HERMESAKI_TOKEN_FILE=/private/path/mailbox-token\nhermesaki messages --inbox ${id}`,HTTP:`GET ${url}/v1/inboxes/${id}/messages\nAuthorization: Bearer YOUR_MAILBOX_TOKEN`};$('#snippet').textContent=examples[$('#client-kind').value];}
$('#client-kind').onchange=snippet;
async function copy(value){try{await navigator.clipboard.writeText(value);notice('Copied.');}catch{notice('Clipboard unavailable. Select and copy the field manually.',true);}}
$('#copy-token').onclick=()=>copy(token.token);$('#copy-config').onclick=()=>copy($('#snippet').textContent);
$('#check').onclick=()=>run('Checking real MCP mailbox access…',async()=>{await mailbox.mcp('initialize');await mailbox.mcp('tools/list');await mailbox.mcp('tools/call',{name:'list_folders',arguments:{inbox_id:inbox.id}});$('#checked').hidden=false;$('#send-test').hidden=settings.mode!=='development';$('#production-help').hidden=settings.mode==='development';await messages();});
async function messages(){const list=await mailbox.listMessages(inbox.id);$('#messages').replaceChildren();if(!list.length)$('#messages').textContent='No messages yet. Send one, then refresh.';for(const m of list)$('#messages').append(row(m.subject||'(No subject)','Read',()=>run('Reading through MCP…',async()=>{const r=await mailbox.mcp('tools/call',{name:'read_message',arguments:{inbox_id:inbox.id,uid:m.uid}});const body=JSON.parse(r.content[0].text);$('#message-body').hidden=false;$('#message-body').textContent=body.body_text;})));return list;}
let testKey;
$('#send-test').onclick=()=>run('Queueing a local SMTP test message…',async()=>{testKey??=crypto.randomUUID();await owner.localTest(inbox.id,testKey);const current=generation;for(let i=0;i<12;i++){const m=await messages();if(m.some(x=>x.subject==='Hello from Hermesaki')){notice('Your test message arrived through SMTP. Open it to read through MCP.');return;}await new Promise(r=>setTimeout(r,1000));if(generation!==current)return;}notice('Queued, but not received yet. Refresh messages shortly; retry uses the same send key.');});
$('#read').onclick=()=>run('Refreshing messages…',messages);
async function tokens(more=false){if(!more){tokenOffset=0;$('#tokens').replaceChildren();}const p=await owner.overview('tokens',tokenOffset);for(const t of p.items.filter(t=>t.inbox===inbox.id)){const expired=t.expires*1000<Date.now();$('#tokens').append(row(`${t.scopes} · ${t.revoked?'revoked':expired?'expired':'active'}`,t.revoked||expired?'Inactive':'Revoke',()=>{if(t.revoked||expired)return;run('Revoking token…',async()=>{await owner.revokeToken(t.id);if(token?.id===t.id){token=null;mailbox=null;$('#mail-token').value='';$('#issued').hidden=true;$('#checked').hidden=true;}await tokens();});}));}tokenOffset+=50;$('#more-tokens').hidden=!p.has_more;}
$('#more-tokens').onclick=()=>run('Loading tokens…',()=>tokens(true));
$('#more').onclick=()=>run('Loading inboxes…',()=>list(true));$('#refresh').onclick=()=>run('Refreshing inboxes…',()=>list());
$('#back').onclick=()=>run('Loading inboxes…',async()=>{generation++;testKey=undefined;token=null;mailbox=null;$('#mail-token').value='';show('create');await list();});
$('#delete').onclick=()=>run('Deleting inbox…',async()=>{if($('#delete-email').value!==inbox.email){notice('Type the exact email address to confirm deletion.',true);return;}await owner.deleteInbox(inbox.id,$('#delete-email').value);token=null;mailbox=null;$('#mail-token').value='';show('create');await list();});
$('#logout').onclick=()=>{generation++;owner=null;mailbox=null;token=null;$('#mail-token').value='';$('#logout').hidden=true;$('#inboxes').replaceChildren();$('#messages').replaceChildren();$('#message-body').textContent='';show('login');notice('Disconnected.');};
