import {Hermesaki} from '../client.js';
export async function mountAgentAccess(root){
 let mcpPanel;const api=new Hermesaki({baseUrl:location.origin,token:''});let offset=0,boxes=[];
 root.innerHTML=`<h2>Connected agents &amp; access keys</h2><p>Give an agent access to a mailbox. Each key has its own permissions and expiry.</p><button class="btn primary" id="access-new">Issue access key</button><form id="access-form" hidden><label>Mailbox<select class="input" id="access-inbox" required></select></label><label>Permissions<select class="input" id="access-scope"><option value="read">Read only</option><option value="write">Read and send mail</option></select></label><label>Expires after<select class="input" id="access-ttl"><option value="86400">1 day</option><option value="604800">7 days</option><option value="2592000" selected>30 days</option></select></label><button class="btn primary">Create access key</button></form><p id="access-status" role="status"></p><div id="access-secret" hidden><label>New access key<input class="input" id="access-value" readonly type="password"></label><button class="btn" id="access-reveal">Show key</button><button class="btn" id="access-copy">Copy key</button><p>Save this key now. It is only shown when issued. Use it as the bearer token when connecting your agent.</p></div><div id="access-list" class="table-wrap"></div><div class="pagination"><button class="btn" id="access-prev">Previous</button><span id="access-page"></span><button class="btn" id="access-next">Next</button></div>`;
 const $=id=>root.querySelector('#'+id);const status=text=>$('access-status').textContent=text;
 async function list(){const p=await api.overview('tokens',offset);const table=document.createElement('table');const head=table.createTHead().insertRow();for(const name of ['Mailbox','Permissions','Expires','Status','Actions']){const th=document.createElement('th');th.textContent=name;head.append(th)}const body=table.createTBody();for(const key of p.items){const expired=key.expires*1000<=Date.now();const state=key.revoked?'Revoked':expired?'Expired':'Active';const row=body.insertRow();for(const value of [boxes.find(b=>b.id===key.inbox)?.email||key.inbox||'Operator',String(key.scopes),new Date(key.expires*1000).toLocaleString(),state])row.insertCell().textContent=value;const button=document.createElement('button');button.className='btn';button.textContent='Revoke';button.disabled=state!=='Active';button.onclick=async()=>{button.disabled=true;try{await api.revokeToken(key.id);$('access-secret').hidden=true;$('access-value').value='';mcpPanel?.clearKey();status('Access key revoked.');await list()}catch{status('Could not revoke the key. Try again.');button.disabled=false}};row.insertCell().append(button)}$('access-list').replaceChildren(table);if(!p.items.length)$('access-list').textContent='No access keys yet. Issue one to connect an agent.';$('access-prev').disabled=offset===0;$('access-next').disabled=!p.has_more;$('access-page').textContent='Page '+(offset/50+1)}
 try{let start=0,p;do{p=await api.listInboxes(start);boxes.push(...p.items);start+=50}while(p.has_more);for(const box of boxes.filter(b=>b.active)){const option=document.createElement('option');option.value=box.id;option.textContent=box.email;$('access-inbox').append(option)}$('access-new').disabled=!$('access-inbox').options.length;if($('access-new').disabled)status('Create an inbox first, then issue an access key here.');await list()}catch{status('Could not load agent access. Reload this page to try again.')}
 $('access-new').onclick=()=>{$('access-form').hidden=false;$('access-inbox').focus()};
 $('access-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const key=await api.createToken($('access-inbox').value,$('access-scope').value==='write'?['mail.read','mail.write']:['mail.read'],Number($('access-ttl').value));$('access-value').value=key.token;$('access-value').type='password';$('access-reveal').textContent='Show key';$('access-secret').hidden=false;$('access-form').hidden=true;mcpPanel?.setKey($('access-inbox').value,key.token);status('Access key created. Scroll to Connect via MCP for the complete configuration.');offset=0;await list()}catch{status('Could not issue an access key. Check the mailbox and try again.')}finally{button.disabled=false}};
 $('access-reveal').onclick=()=>{const hidden=$('access-value').type==='password';$('access-value').type=hidden?'text':'password';$('access-reveal').textContent=hidden?'Hide key':'Show key'};
 $('access-copy').onclick=async()=>{try{await navigator.clipboard.writeText($('access-value').value);status('Key copied.')}catch{status('Select the key and copy it manually.')}};
 mcpPanel=document.createElement('section');mcpPanel.id='mcp-connection';root.append(mcpPanel);const {mountMcpConnection}=await import('./mcp-connection.js');await mountMcpConnection(mcpPanel,boxes);
 for(const [id,delta] of [['access-prev',-50],['access-next',50]])$(id).onclick=async()=>{offset=Math.max(0,offset+delta);try{await list()}catch{status('Could not load this page. Try again.')}};
}
