// Operates only on explicit operator actions. No provider writes during rendering.
export function mountInfrastructure(root,credential){
 root.innerHTML=`<h3>Cloudflare configuration</h3><p>Read the current provider state, then review one change at a time. Existing website records and Access rules are preserved.</p><details><summary>Connect or replace Cloudflare credential</summary><label>Cloudflare API token<input type="password" autocomplete="off" data-token></label><button data-connect>Connect Cloudflare</button><p>The credential is encrypted on the server. Read access is checked now; write permission is checked when applying a change.</p></details><button data-refresh>Refresh from Cloudflare</button><p data-status role="status"></p><div data-editor hidden><label>Configuration type<select data-kind><option value="dns">Mail DNS record</option><option value="route">Tunnel origin</option><option value="policy">Access policy</option></select></label><label>Resource<select data-resource></select></label><div data-fields></div><button data-review>Review change</button><section data-plan hidden><h3>Review before applying</h3><p>These are live infrastructure changes. DNS and origin changes can interrupt delivery or access. Adding an email grants that identity access through this policy.</p><pre data-diff></pre><label><input type="checkbox" data-confirm> Apply this exact reviewed change</label><button data-apply disabled>Apply change</button></section></div>`;
 const $=s=>root.querySelector(s);let inventory=null,selected=null,plan=null,busy=false;
 const status=t=>$('[data-status]').textContent=t;
 async function api(path,body){const r=await fetch('/v1/operator/infrastructure'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'provider_unavailable');return d}
 async function run(fn){if(busy)return;busy=true;root.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn()}catch(e){status('Could not complete this action: '+e.message.replaceAll('_',' ')+'. No automatic retry was made.')}finally{busy=false;root.querySelectorAll('button').forEach(b=>b.disabled=false);$('[data-apply]').disabled=!$('[data-confirm]').checked}}
 function reset(){plan=null;$('[data-plan]').hidden=true;$('[data-confirm]').checked=false}
 function fields(){reset();const rows=inventory[$('[data-kind]').value==='dns'?'dns':$('[data-kind]').value==='route'?'routes':'policies'];selected=rows[Number($('[data-resource]').value)];const f=$('[data-fields]');f.replaceChildren();if(!selected)return;function input(label,key,value){const l=document.createElement('label');l.textContent=label;const i=document.createElement('input');i.dataset.field=key;i.value=value;l.append(i);f.append(l)}
 if($('[data-kind]').value==='dns'){input('Record content','content',selected.content);input('TTL (seconds; 1 = automatic)','ttl',selected.ttl);if(selected.type==='MX')input('MX priority','priority',selected.priority)}else if($('[data-kind]').value==='route')input('Origin URL','service',selected.service);else{input('Policy name','name',selected.name);input('Additional email addresses (comma separated)','add_emails','');const p=document.createElement('p');p.textContent='Existing allowed identities, requirements and exclusions remain unchanged. Removing them requires a separate recovery-aware policy migration.';f.append(p)}}
 function choices(){const select=$('[data-resource]');select.replaceChildren();const rows=inventory[$('[data-kind]').value==='dns'?'dns':$('[data-kind]').value==='route'?'routes':'policies'];rows.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=r.type?r.type+' · '+r.name:r.hostname+(r.name?' · '+r.name:'');select.append(o)});fields()}
 function show(d){inventory=d;$('[data-editor]').hidden=false;status('Provider state read at '+new Date(d.checked_at*1000).toLocaleString()+'.');choices();if(d.pending_plan?.state==='applying'){plan=d.pending_plan;$('[data-plan]').hidden=false;$('[data-diff]').textContent=JSON.stringify({before:plan.before,after:plan.after},null,2);status('A previous change needs verification. Apply checks its result without repeating the write.')}}
 $('[data-connect]').onclick=()=>run(async()=>{const token=$('[data-token]').value;$('[data-token]').value='';const d=await api('/connect',{token});show(d)});
 $('[data-refresh]').onclick=()=>run(async()=>show(await api('')));
 $('[data-kind]').onchange=choices;$('[data-resource]').onchange=fields;
 $('[data-review]').onclick=()=>run(async()=>{if(!selected)throw Error('select_a_resource');const kind=$('[data-kind]').value,change={};root.querySelectorAll('[data-field]').forEach(i=>{change[i.dataset.field]=['ttl','priority'].includes(i.dataset.field)?Number(i.value):i.dataset.field==='add_emails'?i.value.split(',').map(s=>s.trim()).filter(Boolean):i.value});const id=kind==='dns'?selected.id:kind==='route'?selected.tunnel_id+'|'+selected.hostname:selected.app_id+'|'+selected.id;plan=await api('/plan',{kind,id,change});$('[data-plan]').hidden=false;$('[data-diff]').textContent=JSON.stringify({before:plan.before,after:plan.after},null,2);$('[data-confirm]').checked=false;status('Plan prepared. Nothing has been changed. Expires in 10 minutes.');});
 $('[data-confirm]').onchange=()=>{$('[data-apply]').disabled=!$('[data-confirm]').checked};
 $('[data-apply]').onclick=()=>run(async()=>{if(!plan||!$('[data-confirm]').checked)return;await api('/apply',{confirm_plan_id:plan.id});show(await api(''));status('Change applied and read back from Cloudflare.');});
}
