import {connectionPrompt} from './mcp-prompt.js';

const headers={Authorization:'Bearer ${HERMESAKI_MAILBOX_KEY}','CF-Access-Client-Id':'${CF_ACCESS_CLIENT_ID}','CF-Access-Client-Secret':'${CF_ACCESS_CLIENT_SECRET}','User-Agent':'Hermesaki/0.1'};
const endpoint='https://hermesaki.your-domain.com/mcp';
const json=value=>JSON.stringify(value,null,2);
const apps=[
 {id:'codex',name:'Codex',language:'ini',label:'TOML',intro:'Merge this entry into ~/.codex/config.toml. Codex desktop and CLI share this configuration. Set the three environment variables through your private secret setup before launching Codex.',code:`[mcp_servers.hermesaki]
url = "${endpoint}"
bearer_token_env_var = "HERMESAKI_MAILBOX_KEY"

[mcp_servers.hermesaki.http_headers]
User-Agent = "Hermesaki/0.1"

[mcp_servers.hermesaki.env_http_headers]
CF-Access-Client-Id = "CF_ACCESS_CLIENT_ID"
CF-Access-Client-Secret = "CF_ACCESS_CLIENT_SECRET"`,after:'Restart the connection in Settings → MCP servers, or start a new CLI session and use /mcp to check it. Desktop launches may not inherit terminal exports; use supported private header settings if your environment is unavailable.',source:'https://learn.chatgpt.com/docs/extend/mcp?surface=cli'},
 {id:'claude-code',name:'Claude Code',language:'json',intro:'Merge this into .mcp.json in the project where you use Claude Code. The placeholders reference environment variables; keep the actual values in your private environment.',code:json({mcpServers:{hermesaki:{type:'http',url:endpoint,headers}}}),after:'Start Claude Code with those variables available, approve the project MCP server when prompted, then use /mcp to check its connection. Registration alone does not verify the credentials.',source:'https://code.claude.com/docs/en/mcp'},
 {id:'claude-desktop',name:'Claude Desktop',language:'json',intro:'Use the local MCP configuration: Settings → Developer → Edit Config. Merge the entry below into claude_desktop_config.json. Install Node.js first so npx is available; use its absolute path if the desktop app cannot find it.',code:json({mcpServers:{hermesaki:{command:'npx',args:['-y','mcp-remote@0.13.5',endpoint,'--transport','http-only','--header-file','/ABSOLUTE/PRIVATE/PATH/hermesaki-headers.txt']}}}),after:'Replace the path with a private file on your computer. Quit and reopen Claude Desktop after saving. This bridge runs locally; the URL-only hosted connector flow does not document support for these custom authentication headers.',source:'https://modelcontextprotocol.io/docs/develop/connect-local-servers',extra:true},
 {id:'opencode',name:'OpenCode',language:'json',intro:'Merge this into ~/.config/opencode/opencode.json for your user, or opencode.json for this project. Supply the referenced environment variables privately before launching OpenCode.',code:json({$schema:'https://opencode.ai/config.json',mcp:{hermesaki:{type:'remote',url:endpoint,enabled:true,oauth:false,headers:Object.fromEntries(Object.entries(headers).map(([k,v])=>[k,v.replace(/\$\{([^}]+)\}/g,'{env:$1}')]))}}}),after:'Restart OpenCode and check the MCP connection. OAuth is disabled here because Hermesaki uses a mailbox bearer key and, when enabled, Cloudflare service headers.',source:'https://opencode.ai/docs/mcp-servers/'},
 {id:'grok',name:'Grok',language:'ini',label:'TOML',intro:'For Grok Build / CLI, merge this into ~/.grok/config.toml. A project can instead use .grok/config.toml. Supply the referenced environment variables privately before launching Grok. This is the local agent, not the grok.com chat website.',code:`[mcp_servers.hermesaki]
url = "${endpoint}"

[mcp_servers.hermesaki.headers]
Authorization = "Bearer \${HERMESAKI_MAILBOX_KEY}"
CF-Access-Client-Id = "\${CF_ACCESS_CLIENT_ID}"
CF-Access-Client-Secret = "\${CF_ACCESS_CLIENT_SECRET}"
User-Agent = "Hermesaki/0.1"`,after:'Open /mcps in Grok and press r to refresh after editing. Use grok mcp doctor hermesaki to diagnose the connection, then verify list_folders in the agent. Preserve other settings and check for project entries that override this server.',source:'https://docs.x.ai/build/features/mcp-servers'},
 {id:'cursor',name:'Cursor',language:'json',intro:'Merge this into ~/.cursor/mcp.json for all projects, or .cursor/mcp.json inside one project. Cursor resolves ${env:NAME} from its environment. Make the referenced variables available to the Cursor app; terminal exports may not reach an app launched from the desktop.',code:json({mcpServers:{hermesaki:{url:endpoint,headers:Object.fromEntries(Object.entries(headers).map(([k,v])=>[k,v.replace(/\$\{([^}]+)\}/g,'${env:$1}')]))}}}),after:'Reload Cursor, then check that Hermesaki is enabled in its MCP settings and its tools are available to Agent. Use HTTP headers for the mailbox key and Cloudflare service credentials; do not put them in OAuth auth fields.',source:'https://cursor.com/docs/mcp'},
 {id:'other',name:'Other clients',language:'json',intro:'Choose a client that supports Streamable HTTP and custom authentication headers. The values below describe the connection; adapt them to that client’s configuration format.',code:json({url:endpoint,transport:'Streamable HTTP',headers:{Authorization:'Bearer YOUR_MAILBOX_ACCESS_KEY','CF-Access-Client-Id':'YOUR_SERVICE_CLIENT_ID','CF-Access-Client-Secret':'YOUR_SERVICE_CLIENT_SECRET'}}),after:'A URL-only field is insufficient for this authentication scheme. If the app only supports local stdio servers, check whether it supports a local bridge such as the Claude Desktop example. There is no universal install command across MCP apps.',source:'https://modelcontextprotocol.io/docs/learn/client-concepts'}
];
const escape=value=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const example=(text,language,label)=>`<pre><code data-language="${language}" data-label="${label||({json:"JSON",http:"HTTP",plaintext:"Text"})[language]||language}">${escape(text)}</code></pre>`;

export function mountMcpGuide(root,basePath){
 const selected=apps.find(app=>app.id===new URLSearchParams(location.search).get('app'))||apps[0];
 root.innerHTML=`<p>Connect an existing Hermesaki mailbox to your agent app. Choose your app, copy the prompt, and let your agent configure the connection.</p>
 <nav class="mcp-apps" aria-label="MCP client">${apps.map(app=>`<a href="${basePath}/connect-with-mcp?app=${app.id}" aria-current="${app===selected?'page':'false'}">${app.name}</a>`).join('')}</nav>
 <section class="mcp-prompt-card"><h2>Let your agent set it up</h2><p>Copy this prompt into ${selected.name==='Other clients'?'your agent app':selected.name}. It asks for missing details and verifies the connection. Credentials are entered privately during setup.</p><button type="button" class="btn" data-copy-prompt>Copy setup prompt</button><details><summary>Read the prompt</summary><pre class="mcp-prompt-text"></pre></details></section>
 <h2>Have these ready</h2><p><a href="${basePath}/cloudflare-credentials">Get Cloudflare credentials and set environment variables →</a> — step-by-step screenshots for your computer.</p><p>In your Hermesaki dashboard, open <strong>Agent access</strong> and select the mailbox. Get its MCP URL, email address, inbox ID and scoped access key. Choose read-only access, or read and send if your agent should send mail.</p><p>If Cloudflare Access is enabled, also provide the service client ID and secret authorized for that hostname. Remove both Cloudflare headers from the examples when Access is not enabled. Keep all real keys out of project files and copied prompts.</p>
 <details class="mcp-manual" open><summary>Set up ${selected.name==='Other clients'?'your client':selected.name} manually</summary><p>${selected.intro}</p><p>Replace the example endpoint with your dashboard’s MCP URL. Merge the entry into your existing configuration.</p>${example(selected.code,selected.language,selected.label)}<p>${selected.after}</p>
 ${selected.extra?`<p>The private header file contains one header per line. Replace the placeholders inside that file and restrict it to your user (on macOS/Linux, <code>chmod 600 /absolute/path/hermesaki-headers.txt</code>).</p>${example('Authorization: Bearer YOUR_MAILBOX_ACCESS_KEY\nCF-Access-Client-Id: YOUR_SERVICE_CLIENT_ID\nCF-Access-Client-Secret: YOUR_SERVICE_CLIENT_SECRET\nUser-Agent: Hermesaki/0.1','http','Headers')}<p>Uses the third-party <a href="https://github.com/punkpeye/mcp-remote">mcp-remote bridge</a>, version 0.13.5. Claude hosted connectors use a separate <a href="https://support.claude.com/en/articles/11175166-get-started-with-custom-connectors-using-remote-mcp">connector flow</a>; do not enter Cloudflare service credentials as OAuth credentials.</p>`:''}
 <p><a href="${selected.source}" target="_blank" rel="noopener noreferrer">${selected.name} documentation ↗</a></p></details>
 <h2>Check the connection</h2><p>After reloading the app, ask it to list the mailbox’s folders through Hermesaki MCP using your exact inbox ID. Call <code>get_mailbox</code> first to discover the connected address and inbox ID, then use <code>list_folders</code> to return folders. Being listed in settings is only the first step.</p>${example('Use Hermesaki MCP to call list_folders with inbox_id YOUR_INBOX_ID. Report whether it succeeds. Do not send mail or read message bodies.','plaintext','Verification prompt')}
 <p>If tools are missing, reload the MCP connection and grant access in the app. A Cloudflare login page or 403 usually needs service-token or policy checks; a Hermesaki 401 needs a valid mailbox key. Check the endpoint and the app’s environment before retrying.</p>
 <p>Once connected, ask: “Send an email from my connected mailbox to [recipient]. Subject: [subject]. Body: [body].” Sending requires <code>mail.write</code>. Check the returned job ID with <code>get_send_status</code>; stop on <code>terminal: true</code>. If it is still queued after 15 seconds, report the pending job instead of investigating infrastructure. SMTP submission is separate from receipt; check the recipient’s inbox and Spam folder.</p>`;
 const prompt=connectionPrompt({app:selected.name==='Other clients'?'my agent app':selected.name});
 root.querySelector('.mcp-prompt-text').textContent=prompt;
 const button=root.querySelector('[data-copy-prompt]');
 button.onclick=async()=>{try{await navigator.clipboard.writeText(prompt);button.textContent='Copied'}catch{button.textContent='Select prompt';root.querySelector('details').open=true;const range=document.createRange();range.selectNodeContents(root.querySelector('.mcp-prompt-text'));getSelection().removeAllRanges();getSelection().addRange(range)}setTimeout(()=>button.textContent='Copy setup prompt',2000)};
}
