import hljs from './highlight.js';
export function mountDocs(root){
 const source=document.createElement('div');source.append(...root.childNodes);
 const pages=[];let current;
 const names={'Build with your inbox.':'Overview','API and authentication':'Authentication','Routes':'API reference','Local example':'Connect with MCP','TypeScript SDK and CLI':'TypeScript SDK','Real onboarding':'Create an agent inbox'};
 function start(title){current={title:names[title]||title,nodes:[]};current.id=current.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');pages.push(current)}
 for(const node of source.childNodes){if(node.nodeType!==1)continue;if(node.tagName==='SECTION'){for(const child of [...node.children]){if(/^H[23]$/.test(child.tagName))start(child.textContent);else if(current)current.nodes.push(child)}}else if(node.tagName==='H1')start(node.textContent);else if(current&&node.id!=='copy-status')current.nodes.push(node)}
 root.classList.add('docs-reader');root.innerHTML='<aside class="docs-nav"><label for="docs-search">Search documentation</label><input id="docs-search" class="input" type="search" placeholder="Search guides, endpoints…"><nav aria-label="Documentation chapters"></nav><p class="docs-no-results" hidden>No matching pages.</p></aside><article class="docs-article"><div class="docs-breadcrumb">Documentation</div><h1></h1><div class="docs-content"></div><div class="docs-pagination"></div><p class="docs-copy-status" role="status" aria-live="polite"></p></article>';
 const nav=root.querySelector('.docs-nav nav'),content=root.querySelector('.docs-content');let selected;
 pages.forEach(page=>{const a=document.createElement('a');a.href='#'+page.id;a.textContent=page.title;a.onclick=e=>{e.preventDefault();show(page.id);history.replaceState({},'','/docs#'+page.id)};page.link=a;nav.append(a)});
 function codeBlocks(){content.querySelectorAll('pre code').forEach(code=>{const text=code.textContent;const language=/^\s*(import |const |await )/.test(text)?'typescript':/^\s*[\[{]/.test(text)?'json':'bash';code.innerHTML=hljs.highlight(text,{language,ignoreIllegals:true}).value;code.className='hljs language-'+language;const pre=code.parentElement;let wrapper=pre.parentElement;if(!wrapper.classList.contains('example')){wrapper=document.createElement('div');wrapper.className='example';pre.replaceWith(wrapper);wrapper.append(pre)}wrapper.querySelectorAll('button').forEach(b=>b.remove());const bar=document.createElement('div');bar.className='docs-codebar';const label=document.createElement('span');label.textContent=({bash:'Shell',typescript:'TypeScript',json:'JSON',http:'HTTP'})[language];const copy=document.createElement('button');copy.className='btn';copy.dataset.variant='ghost';copy.textContent='Copy';copy.setAttribute('aria-label','Copy '+label.textContent+' example');copy.onclick=async()=>{try{await navigator.clipboard.writeText(text);copy.textContent='Copied';root.querySelector('.docs-copy-status').textContent='Code copied to clipboard.'}catch{root.querySelector('.docs-copy-status').textContent='Select the code and copy it manually.'}};bar.append(label,copy);wrapper.prepend(bar)})}
 function show(id){const page=pages.find(p=>p.id===id)||pages[0];selected=page;root.querySelector('.docs-article h1').textContent=page.title;content.replaceChildren(...page.nodes.map(n=>n.cloneNode(true)));pages.forEach(p=>p.link.setAttribute('aria-current',p===page?'page':'false'));codeBlocks();content.querySelectorAll('td:first-child code').forEach(code=>{const match=code.textContent.match(/^(GET|POST|DELETE|PUT|PATCH) (.*)$/);if(match){code.textContent=match[2];const badge=document.createElement('span');badge.className='docs-method';badge.dataset.method=match[1];badge.textContent=match[1];code.before(badge)}});const pager=root.querySelector('.docs-pagination');pager.replaceChildren();const index=pages.indexOf(page);for(const [i,label] of [[index-1,'Previous'],[index+1,'Next']])if(pages[i]){const a=document.createElement('a');a.href='#'+pages[i].id;a.textContent=label+': '+pages[i].title;a.onclick=e=>{e.preventDefault();show(pages[i].id);history.replaceState({},'','/docs#'+pages[i].id)};pager.append(a)}root.querySelector('.docs-copy-status').textContent='';root.querySelector('.docs-article').scrollIntoView({block:'start',behavior:'instant'})}
 root.querySelector('#docs-search').oninput=e=>{const q=e.target.value.trim().toLowerCase();let matches=0;pages.forEach(p=>{const match=(p.title+' '+p.nodes.map(n=>n.textContent).join(' ')).toLowerCase().includes(q);p.link.hidden=!match;if(match)matches++});root.querySelector('.docs-no-results').hidden=matches!==0};
 show(location.hash.slice(1));
}
