import {enhanceSecrets} from '../design-system/secret-field.js';
const sections={general:'General',dns:'Mail DNS',network:'Network',access:'Access'};
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n};
async function api(path,body){const r=await fetch('/v1/operator/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error((d.error||'Request failed').replaceAll('_',' '));return d}
export async function mountSettings(root,data){
 let inventory=data.infrastructure||{};
 const nav=node('nav',null,'settings-tabs');nav.setAttribute('aria-label','Settings sections');const content=node('div',null,'settings-stack');root.replaceChildren(nav,content);
 function card(title,description,values,{hint='Review changes before applying.',save,secret=false}={}){
  const c=node('section',null,'setting-card'),body=node('div',null,'setting-body'),footer=node('footer'),status=node('p',hint),actions=node('div',null,'form-actions');
  body.append(node('h2',title),node('p',description));const value=node('div',null,'setting-value');for(const [k,v]of Object.entries(values)){const row=node('div');row.append(node('span',k),node('code',String(v??'Not configured')));value.append(row)}body.append(value);footer.append(status,actions);c.append(body,footer);content.append(c);
  if(!save){actions.append(node('span','Read only','setting-readonly'));return}
  const edit=node('button','Edit','btn');edit.dataset.variant='outline';actions.append(edit);
  edit.onclick=()=>{value.hidden=true;const form=node('form',null,'setting-fields');const inputs=[];for(const[k,v]of Object.entries(values)){const label=node('label',k),input=node(k==='Content'?'textarea':'input');input.name=k;input.value=secret?'':String(v??'');input.required=k!=='Additional email addresses';if(secret)input.type='password';if(k.includes('URL'))input.type='url';if(k==='TTL'||k==='Priority'){input.type='number';input.min=k==='TTL'?'1':'0';input.max=k==='TTL'?'86400':'65535'}label.append(input);form.append(label);inputs.push(input)}body.append(form);enhanceSecrets(form);
   const cancel=node('button','Cancel','btn'),review=node('button',secret?'Save':'Review changes','btn');review.dataset.variant='primary';review.disabled=true;actions.replaceChildren(cancel,review);const reset=()=>{form.remove();value.hidden=false;actions.replaceChildren(edit);status.textContent=hint};cancel.onclick=reset;form.oninput=()=>{review.disabled=inputs.every(i=>i.value===String(values[i.name]??''))};review.onclick=async()=>{if(!form.reportValidity())return;review.disabled=true;cancel.disabled=true;try{const next=Object.fromEntries(inputs.map(i=>[i.name,i.value]));await save(next,c,status,actions,reset); }catch(e){status.textContent=e.message;review.disabled=false;cancel.disabled=false}};form.onsubmit=e=>{e.preventDefault();if(!review.disabled)review.click()};inputs[0]?.focus();
  };
 }
 async function reviewChange(path,body,next,c,status,actions,reset){
  const plan=await api(path+'/plan',body);const diff=node('div',null,'setting-review');diff.append(node('h3','Review change'));for(const[label,value]of [['Current',plan.before],['New',plan.after]]){diff.append(node('p',label),node('pre',typeof value==='object'?JSON.stringify(value,null,2):String(value)))}c.querySelector('.setting-body').append(diff);c.querySelectorAll('input,textarea').forEach(i=>i.disabled=true);const cancel=node('button','Cancel','btn'),apply=node('button','Apply change','btn');apply.dataset.variant='primary';actions.replaceChildren(cancel,apply);cancel.onclick=()=>{diff.remove();reset()};status.textContent=plan.effect||'Apply only this reviewed change. The plan expires in 10 minutes.';apply.onclick=async()=>{apply.disabled=true;cancel.disabled=true;try{await api(path+'/apply',{confirm_plan_id:plan.id});const fresh=await api('configuration');data=fresh;inventory=fresh.infrastructure||inventory;root.dispatchEvent(new Event('settings-updated'));render();}catch(e){status.textContent=e.message;apply.disabled=false;cancel.disabled=false}};
 }
 function render(){if(!root.isConnected)return;const tab=sections[location.pathname.split('/')[2]||location.hash.slice(1)]?(location.pathname.split('/')[2]||location.hash.slice(1)):'general';history.replaceState({},'', '/settings/'+tab);nav.replaceChildren();content.replaceChildren();for(const[id,label]of Object.entries(sections)){const a=node('a',label);a.href='/settings/'+id;if(id===tab)a.setAttribute('aria-current','page');a.onclick=e=>{if(e.metaKey||e.ctrlKey)return;e.preventDefault();history.pushState({},'',a.href);render()};nav.append(a)}
 if(tab==='general'){
 card('Webmail URL','Where you open mail in your browser.',{'Webmail URL':data.webmail_url},{save:(n,...rest)=>reviewChange('configuration',{webmail_url:n['Webmail URL']},n,...rest),hint:'Updates the Open webmail link.'});
 card('Email domain','The domain used for mailbox addresses.',{Domain:data.domain},{hint:'Changing the domain requires a mailbox migration.'});
 card('Mail server','Installed connection settings.',{Hostname:data.mail_host,'IMAP port':data.imap_port,'SMTP port':data.smtp_port},{hint:'Managed by the installation. Changes require a coordinated server update.'});
 card('Delivery limits','Limits enforced by the server.',{'Message size':data.message_size_limit_bytes?`${data.message_size_limit_bytes/1048576} MB`:'Not reported','Delivery attempts':data.delivery_attempt_limit??'Not reported','Webhook hosts':(data.webhook_hosts||[]).join(', ')||'None'},{hint:'The current backend does not support editing these limits.'});
 card('Dashboard access','Installed Cloudflare identity configuration.',{'Dashboard URL':data.operator_url,'Access team':data.cloudflare_access_team||'Not reported','Identity verification':data.cloudflare_identity_verification?'Enabled':'Disabled'},{hint:'Identity configuration is managed by the installation.'});return;
 }
 const key={dns:'dns',network:'routes',access:'policies'}[tab],kind={dns:'dns',network:'route',access:'policy'}[tab];
 const toolbar=node('div',null,'settings-toolbar'),refresh=node('button','Refresh from Cloudflare','btn'),message=node('p');toolbar.append(refresh,message);content.append(toolbar);refresh.onclick=async()=>{refresh.disabled=true;try{inventory=await api('infrastructure');render()}catch(e){message.textContent=e.message;refresh.disabled=false}};
 const rows=inventory[key]||[];
 if(!rows.length)content.append(node('p','No saved '+sections[tab].toLowerCase()+' records. Connect Cloudflare below, then refresh the inventory.','setting-empty'));
 for(const r of rows){const values=kind==='dns'?{Content:r.content,TTL:r.ttl,...(r.type==='MX'?{Priority:r.priority}:{})}:kind==='route'?{'Origin URL':r.service}:{'Policy name':r.name,'Additional email addresses':''};const id=kind==='dns'?r.id:kind==='route'?r.tunnel_id+'|'+r.hostname:r.app_id+'|'+r.id;
 card(kind==='dns'?r.type+' · '+r.name:r.hostname,kind==='dns'?'Mail DNS record':kind==='route'?'Tunnel origin':'Access policy · '+r.name,values,{hint:kind==='policy'?'Existing identities, requirements and exclusions are preserved.':'Resource identity is fixed; edit its supported values here.',save:(n,...rest)=>{const change=kind==='dns'?{content:n.Content,ttl:Number(n.TTL),...(r.type==='MX'?{priority:Number(n.Priority)}:{})}:kind==='route'?{service:n['Origin URL']}:{name:n['Policy name'],add_emails:n['Additional email addresses'].split(',').map(s=>s.trim()).filter(Boolean)};return reviewChange('infrastructure',{kind,id,change},n,...rest)}});
 }
 card('Cloudflare API credential','Used to read and update infrastructure. This is separate from your agent’s service credentials.',{'API token':''},{secret:true,hint:'The token is encrypted on the server.',save:async(n,c,status,actions,reset)=>{inventory=await api('infrastructure/connect',{token:n['API token']});render()}});
 }
 render();
}
