import type { Dispatch, SetStateAction, RefObject } from "react";
export type Surface = string;
export type Step = {
  id: string;
  label: string;
  surface: Surface;
  path: string;
  expected: string;
  actor?: string;
};
export type Workflow = {
  id: string;
  title: string;
  description: string;
  nodes: Step[];
  edges: [string, string][];
  route: string[];
  version?: string;
  defaultActor?: string;
  titles?: Record<string, string>;
  chapters?: { label: string; steps: string[] }[];
  branches?: { id: string; label: string; steps: string[] }[];
};
export type Capture = {
  stepId: string;
  at: number;
  surface: Surface;
  html: string;
  url: string;
  heading: string;
  guideKey?: string;
  context?: Record<string, string>;
  guide?: Guide;
  targetId?: string;
  click?: boolean;
  verified?: boolean;
  check?: "target" | "input" | "server" | "navigation";
};
export type Recording = {
  id: string;
  workflow: string;
  schemaVersion?: number;
  definition?: Workflow;
  createdAt: string;
  captures: Capture[];
  outcome?: "running" | "passed" | "failed";
  error?: string;
};
export type Perspective = string;
export type Fixture = Record<string, string>;
export type Guide = { caption: string; action: "inspect" | "click" | "fill" };
export type StudioController = {
  cancelRun: () => void;
  libraryOpen: boolean;
  reviewView: "timeline" | "map";
  actor: Perspective;
  busy: boolean;
  running: boolean;
  chooseActor: (next: Perspective) => void;
  actors: { id: string; label: string }[];
  journeys: Workflow[];
  workflow: Workflow;
  chooseWorkflow: (id: string, perspective?: Perspective) => void;
  journeyTitle: (id: string, actor: Perspective, fallback: string) => string;
  setLibraryOpen: Dispatch<SetStateAction<boolean>>;
  setReviewView: Dispatch<SetStateAction<"timeline" | "map">>;
  recordings: Recording[];
  setRecording: Dispatch<SetStateAction<Recording | null>>;
  setMode: Dispatch<SetStateAction<"live" | "replay">>;
  setPlaying: Dispatch<SetStateAction<boolean>>;
  setTime: Dispatch<SetStateAction<number>>;
  recordingProgress: (
    run: Recording,
    workflow: Workflow,
  ) => {
    complete: boolean;
    count: number;
    total: number;
    next: string | undefined;
    label: string;
  };
  clock: (ms: number) => string;
  enabled: boolean;
  setActor: Dispatch<SetStateAction<Perspective>>;
  stopRun: RefObject<boolean>;
  defaultActor: (id: string) => Perspective;
  fresh: () => void;
  names: Record<Surface, string>;
  node: Step;
  stage: RefObject<HTMLDivElement | null>;
  surfaces: Surface[];
  playback: {
    playAt: number;
    stepId: string;
    at: number;
    surface: Surface;
    html: string;
    url: string;
    heading: string;
    guideKey?: string;
    context?: Record<string, string>;
    guide?: Guide;
    targetId?: string;
    click?: boolean;
    verified?: boolean;
    check?: "target" | "input" | "server" | "navigation";
  }[];
  time: number;
  handoff: boolean;
  actorName: (id: Perspective) => string;
  stepActor: string;
  mode: "live" | "replay";
  nonce: RefObject<string>;
  frames: RefObject<Partial<Record<Surface, HTMLIFrameElement | null>>>;
  frameUrl: (s: Surface, path: string, nonce: string) => string;
  paths: Record<Surface, string>;
  moveCursor: (x: number, y: number) => void;
  subtitles: boolean;
  guideFor: (workflow: string, step: string) => Guide;
  selected: string;
  crossHandoff: () => void;
  cursor: { x: number; y: number };
  recording: Recording | null;
  activeCaptureAt: number | undefined;
  playing: boolean;
  duration: number;
  setSubtitles: Dispatch<SetStateAction<boolean>>;
  speed: number;
  setSpeed: Dispatch<SetStateAction<number>>;
  captures: Capture[];
  reviewPane: RefObject<HTMLDivElement | null>;
  activeChapter: { label: string; steps: string[] } | undefined;
  branch: string;
  setBranch: Dispatch<SetStateAction<string>>;
  guideState: string;
  fixture: Fixture | null;
  details: { label: string; value: string }[];
  error: string;
  setZoom: Dispatch<SetStateAction<number>>;
  width: number;
  zoom: number;
  height: number;
  graph: {
    x: number;
    y: number;
    id: string;
    label: string;
    surface: Surface;
    path: string;
    expected: string;
    actor?: string;
  }[];
  select: (id: string) => void;
  chapters: { label: string; steps: string[] }[];
  branches: { id: string; label: string; steps: string[] }[];
  record: () => Promise<void>;
  frameName: (nonce: string) => string;
  prepareSnapshot: (capture: Capture) => string;
  saveSubtitles: (enabled: boolean) => void;
};
