// Presentation only: commands are displayed, never executed by the viewer.
export const installation:Record<string,[string,string,string]>={
 clone:['Get the repository','git clone https://github.com/Ansonhkg/hermesaki.git\ncd hermesaki','Repository access is required. Run this on the VPS to avoid a separate upload.'],
 vps:['Connect to your VPS','ssh YOUR_USER@YOUR_VPS\ngit clone https://github.com/Ansonhkg/hermesaki.git\ncd hermesaki','Use a supported Linux VPS with Docker Compose, Python 3.10+, Git and make. SMTP port 25 and reverse DNS must be available.'],
 upload:['Alternative: upload your checkout','rsync -av --exclude=.git --exclude=.runtime --exclude=node_modules --exclude=.venv ./ YOUR_USER@YOUR_VPS:~/hermesaki/','Use this instead of cloning on the VPS. Never upload local credentials or mailbox data as part of the source checkout.'],
 boot:['Start private setup','cd ~/hermesaki\nmake setup','The setup service listens on 127.0.0.1:19200. Keep this terminal running. The wizard provisions mail services after approval.'],
 tunnel:['Open the wizard from your computer','ssh -L 19200:127.0.0.1:19200 YOUR_USER@YOUR_VPS','Run this in another terminal on your computer, then open http://127.0.0.1:19200. Do not publicly expose the bootstrap port.'],
 bootstrap:['Find the first credential','cat .runtime/setup/bootstrap-token','Read this privately on the VPS inside the repository. Paste it into the wizard. Generate and save a NEW owner credential before claiming. No actual secret is shown here.']
};
export function installPage(id:string){const [title,command,detail]=installation[id]||installation.clone;const escape=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');return `<!doctype html><html><head><title>Installation walkthrough</title></head><body style="background:#10170e;color:#edf5e8;font:18px/1.6 system-ui;padding:48px"><p>Hermesaki · Installation guide</p><p>SIMULATED TERMINAL · Commands are not executed</p><main id="install-step"><h1>${title}</h1><pre style="padding:24px;background:#22301b;white-space:pre-wrap">${escape(command)}</pre><p>${detail}</p></main><script type="module" src="/bridge.ts"></script></body></html>`;}
